export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SING_IN = '/signin'
export const HOME = '/home'
export const ACCOUNT = '/account'
export const ADMIN = '/admin'
export const PASSWORD_FORGET = '/pw-forget'